# basic options
title: Laboratory of Evolutionary Genetics @ USP
author: Diogo Meyer
email: diogo@ib.usp.br
description: Institute of Biosciences, University of São Paulo
twitter_username: meyer_diogo
github_username: diogomeyer

# Build settings
markdown: kramdown
theme: minima
